### ISSUE TITLE
foi arrumar as rotas

### ISSUE THREAD

**Issue by JCDMeira** [joaocorner/url-shortener#1]
há rotas não necessárias e a rota de Links está quebrada.

![image](https://user-images.githubusercontent.com/65555624/200546367-7fe8ed79-675c-418f-aa6a-c735c62c2f42.png)

A rota só com / já é suficiente para que no index seja reconhecido, e a * não é para essa finalidade, é uma rota de erro ou usada para mostrar algum aviso de erro de rotas para o usuário.

E a rota de Links está quebrada
![image](https://user-images.githubusercontent.com/65555624/200546669-b26a89a0-a9a0-4332-92fa-73819bec1eba.png)

**Comment by joaocorner** [comment]
Pesquisei sobre esse tipo de problema, era preciso implementar com HashRouter, não conhecia ainda.
